variables:
  title: "TEI Publisher"
  name: "tei-publisher"
  remote: "http://localhost:8080/exist/apps/tei-publisher/"
  # the prefix under which pages will be available
  context: "/tei-publisher"
  components: 1.35.2
  # components: dev
  cdn: "https://unpkg.com/@teipublisher/pb-components"
  # cdn: "http://localhost:8000"
  languages:
    "bg": "Български"
    "cs": "Česky"
    "zh_CN": "简体中文"
    "zh_TW": "繁體中文"
    "de": "Deutsch"
    "en": "English"
    "es": "Español"
    "el": "ελληνικά"
    "fr": "Français"
    "fi": "Suomi"
    "it": "Italiano"
    "ka": "ქართული"
    "nl": "Nederlands"
    "no": "Norsk"
    "pl": "Polski"
    "pt": "Português"
    "ro": "Română"
    "ru": "русский"
    "sl": "Slovenščina"
    "sv": "Svenska"
    "tr": "Türkçe"
    "uk": "Українська"
collection: true # default: traverse the collection hierary
templates:
  view.html:
    data:
      main:
      title:
        view: single
        xpath: //teiHeader/fileDesc/titleStmt
        user.mode: title
      toc.html: "{{remote}}api/document/{{doc}}/contents?target=transcription&icons=true"
  dta.html:
    data:
      main:
      title:
        view: single
        xpath: //teiHeader/fileDesc/titleStmt/title[@type='main']
        user.header: short
      toc.html: "{{remote}}api/document/{{doc}}/contents?target=transcription&icons=true"
  letter.html:
    data:
      main:
      title:
        view: single
        xpath: //teiHeader/fileDesc/titleStmt/title
        user.header: short
      places:
        user.mode: facets
  facsimile.html:
    data:
      main:
      title:
        view: single
        xpath: //teiHeader/fileDesc/titleStmt
        user.mode: title
      toc.html: "{{remote}}api/document/{{doc}}/contents?target=transcription&icons=true"
  documentation.html:
    data:
      main:
      breadcrumbs:
        user.mode: breadcrumbs
      toc.html: "{{remote}}api/document/{{doc}}/contents?target=transcription&icons=false"
      documentation.css: "{{remote}}templates/pages/documentation.css"
  translation.html:
    data:
      transcription:
        xpath: "! (.//text[@xml:lang = 'la']/body | .//text/body)[1]"
      translation:
        xpath: "//text[@xml:lang='pl']/body"
      breadcrumbs:
        view: single
        user.header: letter
        xpath: //teiHeader
  cortez.html:
    data:
      transcription:
        xpath: "//text[@type='source']"
      translation:
        xpath: "//text[@type='source']"
        map: cortez-translation
      title:
        view: single
        xpath: //teiHeader
        user.mode: title
  cortez-with-translation.html:
    data:
      transcription:
        xpath: "//text[@type='source']"
      translation:
        xpath: "//text[@type='source']"
        map: cortez-translation
      title:
        view: single
        xpath: //teiHeader
        user.mode: title
assets:
  "css": 
    - "{{remote}}resources/css/theme.css"
  "images": 
    - "{{remote}}resources/images/tei-publisher-logo-color.svg"
    - "{{remote}}resources/images/tei-publisher-logo-contrast-color.svg"
    - "{{remote}}resources/images/favicon-16.png"
    - "{{remote}}resources/images/favicon-24.png"
    - "{{remote}}resources/images/favicon-32.png"
    - "{{remote}}resources/images/favicon-64.png"
    - "{{remote}}resources/images/favicon.ico"